Frontend setup
hardkov/human-resources-management pull request #2
Opened 2021-04-15 18:16 UTC by hardkov

Created a new frontend app. The connection with backend can be verified by running the app and checking the console:
![Screenshot from 2021-04-15 20-14-39](https://user-images.githubusercontent.com/28395696/114918341-44cb0100-9e27-11eb-8db4-c54aa41c8620.png)

2021-04-16 06:32 UTC, Petroniuss approved these changes
great ;d Glad that you went with typescript.

2021-04-16 11:13 UTC, Pinioo requested changes
- gradle/wrapper/gradle-wrapper.jar should be included in repo
- react-app/package-lock.json should be included in repo

2021-04-17 12:01 UTC, ChrisFlam3 requested changes
Missing package-lock.json

2021-04-17 18:54 UTC, ChrisFlam3 approved these changes

2021-04-17 18:56 UTC, Pinioo approved these changes

2021-04-17 19:32 UTC, merged