Backend data access
hardkov/human-resources-management pull request #3
Opened 2021-04-17 18:47 UTC by ChrisFlam3

Goal of this PR is to provide data access layer, this include:
-JPA repositories
-API classes for data exchange
-Controllers for requests handling

2021-04-18 08:51 UTC, hardkov approved these changes

2021-04-18 11:00 UTC, kocimski approved these changes

2021-04-18 11:47 UTC, Petroniuss requested changes
All methods in controllers need to be wrapped in ResponseEntity<BodyType>. Returning HttpStatus simply returns a string and sets HTTP status code to ok - 200.

2021-04-19 07:52 UTC, Pinioo approved these changes

2021-04-20 09:11 UTC, Petroniuss approved these changes

2021-04-20 09:23 UTC, merged