Io2021 c 29/feat/applications management
hardkov/human-resources-management pull request #41
Opened 2021-05-18 17:08 UTC by Petroniuss

Added endpoints for both managing applications (meaning updating their status) and creating/fetching applications. 
- for employee
![image](https://user-images.githubusercontent.com/31375809/118693658-8f1b1580-b80b-11eb-87e2-84adff7271a9.png)
- for supervisor
![image](https://user-images.githubusercontent.com/31375809/118693676-9510f680-b80b-11eb-97a4-d836a1be2061.png)

There's still a place for validating payloads received from the client. 
The preferred way of returning an error is via InvalidRequestException which turns a request into BadRequest with a simple string - this should be good enough for the front-end.

Also, right now updating the status of an application doesn't add any Delegation/Bonus/Leave - I'd rather discuss how we want to handle that first.

2021-05-21 12:56 UTC, Pinioo commented on spring-app/src/main/java/com/agh/hr/controllers/employee/ApplicationController.java
> +}
Not sure if this file has any purpose or is just accidentally added

2021-05-21 13:00 UTC, Pinioo requested changes
Everything looks good but I think an endpoint in ApplicationManagementController for fetching single user applications would be useful.

2021-05-22 00:21 UTC, ChrisFlam3 commented
This pull is to be delayed at least to next meeting as discussed with @Petroniuss

2021-05-25 13:53 UTC, Petroniuss commented
I integrated the already discussed code with permissions via this service. I wonder @ChrisFlam3, could we use it in other services? It essentially gives you all users that either are your subordinates or you have permissions to read/modify them (it also takes care of admin case). 

![image](https://user-images.githubusercontent.com/31375809/119509239-c1c78f80-bd70-11eb-9750-5f7556d70f77.png)

I'd like to merge this ASAP so that the front-end could integrate with these endpoints.

2021-05-25 16:47 UTC, merged